"""
Subsets Baloo down to the characters this prototype actually draws, converts to woff2, and
writes src/font.css with the font embedded as a base64 data: URI.

Why inline instead of a normal font file:
  - the first-load request budget is 4 (html, js, catalog.json, first picture). A separate
    font file would be a 5th request, and a Google Fonts <link> would be two plus a DNS
    lookup - on 4G inside an in-app browser that is real time against a 3 second ceiling.
  - a swapped-in fallback font mid-load changes what the player sees in the first second,
    which is the exact second the legibility gate is measuring.

Baloo is the demo's font (Assets/_Game/Demo/Fonts/Normal/Baloo) and is SIL OFL, which permits
web embedding. Re-check the licence if the font is ever swapped.

Run: npm run font:subset   (needs: pip install fonttools brotli)
"""

import base64
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
WEB = HERE.parent
REPO = WEB.parent
SRC_TTF = REPO / "Assets" / "_Game" / "Demo" / "Fonts" / "Normal" / "Baloo" / "Baloo-Regular.ttf"
OUT_WOFF2 = HERE / ".cache" / "Baloo-subset.woff2"
OUT_CSS = WEB / "src" / "font.css"

# Printable ASCII covers every string in the build (labels, praise lines, clue digits).
UNICODES = "U+0020-007E"


def main() -> int:
    if not SRC_TTF.exists():
        print(f"font not found: {SRC_TTF}", file=sys.stderr)
        return 1

    OUT_WOFF2.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        sys.executable,
        "-m",
        "fontTools.subset",
        str(SRC_TTF),
        f"--unicodes={UNICODES}",
        "--flavor=woff2",
        "--layout-features=kern,liga",
        "--desubroutinize",
        "--drop-tables+=DSIG",
        f"--output-file={OUT_WOFF2}",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        return result.returncode

    data = OUT_WOFF2.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    kb = len(data) / 1024
    b64_kb = len(b64) / 1024

    OUT_CSS.write_text(
        "/* GENERATED by scripts/subset-font.py - do not edit by hand.\n"
        f"   Baloo, subset to {UNICODES}: {kb:.1f} KB woff2 -> {b64_kb:.1f} KB base64.\n"
        "   Inlined so the first load stays within 4 requests. */\n"
        "@font-face {\n"
        "  font-family: 'Baloo';\n"
        "  font-style: normal;\n"
        "  font-weight: 400 800;\n"
        "  font-display: block;\n"
        f"  src: url(data:font/woff2;base64,{b64}) format('woff2');\n"
        "}\n",
        encoding="utf8",
    )

    print(f"woff2 {kb:.1f} KB -> base64 {b64_kb:.1f} KB -> {OUT_CSS.relative_to(WEB)}")
    if kb > 18:
        print(f"WARNING: {kb:.1f} KB exceeds the 18 KB font budget", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
